"""Shared runtime configuration limits."""

DEFAULT_MAX_ROUNDS = 30
MAX_ALLOWED_ROUNDS = 100
DEFAULT_ROUND_EXTENSION = 10
DEFAULT_HARD_MAX_ROUNDS = MAX_ALLOWED_ROUNDS
DEFAULT_ROUND_LIMIT_ACTION = "ask"
SUPPORTED_ROUND_LIMIT_ACTIONS = {"ask", "auto", "stop"}
DEFAULT_SECURITY_LEVEL = "normal"
SUPPORTED_SECURITY_LEVELS = {"strict", "normal", "permissive"}
DEFAULT_NOTES_ENABLED = False
DEFAULT_NOTE_ROUTING_ENABLED = False
DEFAULT_NOTE_ROUTING_MODEL = "jev-latest"
DEFAULT_NOTE_ROUTING_CONFIDENCE = 0.85
DEFAULT_NOTE_ROUTING_TIMEOUT = 5.0
DEFAULT_UI_MODE = "stream"
SUPPORTED_UI_MODES = {"stream", "fullscreen"}
DEFAULT_TASK_MODE_ROUTING_ENABLED = False
DEFAULT_TASK_MODE_ROUTING_MODEL = "jev-latest"
DEFAULT_TASK_MODE_ROUTING_CONFIDENCE = 0.85
DEFAULT_TASK_MODE_ROUTING_TIMEOUT = 5.0
DEFAULT_TASK_MODE_ROUTING_LLM_TIMEOUT = 20.0
