"""Shared runtime configuration limits."""

DEFAULT_MAX_ROUNDS = 30
MAX_ALLOWED_ROUNDS = 100
DEFAULT_ROUND_EXTENSION = 10
DEFAULT_HARD_MAX_ROUNDS = MAX_ALLOWED_ROUNDS
DEFAULT_ROUND_LIMIT_ACTION = "ask"
SUPPORTED_ROUND_LIMIT_ACTIONS = {"ask", "auto", "stop"}
DEFAULT_SECURITY_LEVEL = "normal"
SUPPORTED_SECURITY_LEVELS = {"strict", "normal", "permissive"}
DEFAULT_NOTES_ENABLED = False
